
server:
  port: 80
spring:
  application:
    name: springboot-test
  datasource:
    url: jdbc:mysql://127.0.0.1/test?useUnicode=true&amp;characterEncoding=UTF-8
    username: root
    password: root
    driver_class_namel: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    
    max-active: 20
    initial-size: 1
    min-idle: 3
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    poolPreparedStatements: true

logging:
  file: ./springboot.log
  level:
    org.springframework.web: DEBUG
    com.zhushoumao.springboot: DEBUG

#debug: true
